export function env(key: keyof ImportMetaEnv, fallback = ""): string {
  const viteValue = import.meta.env[key];
  if (viteValue !== undefined && viteValue !== "") {
    return viteValue;
  }
  if (typeof process !== "undefined" && process.env[key]) {
    return process.env[key]!;
  }
  return fallback;
}

export const AIRTABLE_BASE_ID = env("VITE_AIRTABLE_BASE_ID");
export const AIRTABLE_API_KEY = env("VITE_AIRTABLE_API_KEY");

export const AIRTABLE_TABLE_NAME = env("VITE_AIRTABLE_TABLE_NAME", "Users");
export const AIRTABLE_EMAIL_FIELD = env("VITE_AIRTABLE_EMAIL_FIELD", "email");
export const AIRTABLE_PASSWORD_FIELD = env("VITE_AIRTABLE_PASSWORD_FIELD", "Password");
export const AIRTABLE_SHOW_HABITS_FIELD = env("VITE_AIRTABLE_SHOW_HABITS_FIELD", "show_habits");
export const AIRTABLE_SHOW_PERSONAL_PROJECTS_FIELD = env("VITE_AIRTABLE_SHOW_PERSONAL_PROJECTS_FIELD", "show_personal_projects");

export const AIRTABLE_HABITS_TABLE_NAME = env("VITE_AIRTABLE_HABITS_TABLE_NAME", "Habits");
export const AIRTABLE_HABITS_USER_ID_FIELD = env("VITE_AIRTABLE_HABITS_USER_ID_FIELD", "user_id");
export const AIRTABLE_HABITS_NAME_FIELD = env("VITE_AIRTABLE_HABITS_NAME_FIELD", "name");
export const AIRTABLE_HABITS_FREQUENCY_FIELD = env("VITE_AIRTABLE_HABITS_FREQUENCY_FIELD", "frequency");
export const AIRTABLE_HABITS_CREATED_AT_FIELD = env("VITE_AIRTABLE_HABITS_CREATED_AT_FIELD", "created_at");
export const AIRTABLE_HABITS_IS_ACTIVE_FIELD = env("VITE_AIRTABLE_HABITS_IS_ACTIVE_FIELD", "is_active");
export const AIRTABLE_HABITS_DELETED_DATE_FIELD = env("VITE_AIRTABLE_HABITS_DELETED_DATE_FIELD", "deleted_date");

export const AIRTABLE_HABITS_LOGS_TABLE_NAME = env("VITE_AIRTABLE_HABITS_LOGS_TABLE_NAME", "HabitsLogs");
export const AIRTABLE_HABITS_LOGS_HABIT_ID_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_HABIT_ID_FIELD", "habit_id");
export const AIRTABLE_HABITS_LOGS_USER_ID_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_USER_ID_FIELD", "user_id");
export const AIRTABLE_HABITS_LOGS_COMPLETED_AT_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_COMPLETED_AT_FIELD", "completed_at");
export const AIRTABLE_HABITS_LOGS_FREQUENCY_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_FREQUENCY_FIELD", "frequency");
export const AIRTABLE_HABITS_LOGS_PERIOD_FIELD = env("VITE_AIRTABLE_HABITS_LOGS_PERIOD_FIELD", "period");


export const AIRTABLE_NOTES_TABLE_NAME = env("VITE_AIRTABLE_NOTES_TABLE_NAME", "Notes");
export const AIRTABLE_NOTES_ID_FIELD = env("VITE_AIRTABLE_NOTES_ID_FIELD", "id");
export const AIRTABLE_NOTES_CONTENT_FIELD = env("VITE_AIRTABLE_NOTES_CONTENT_FIELD", "Notes");
export const AIRTABLE_NOTES_ASSIGNEES_FIELD = env("VITE_AIRTABLE_NOTES_ASSIGNEES_FIELD", "Assignees");
export const AIRTABLE_NOTES_STATUS_FIELD = env("VITE_AIRTABLE_NOTES_STATUS_FIELD", "Status");
export const AIRTABLE_NOTES_ATTACHMENTS_FIELD = env("VITE_AIRTABLE_NOTES_ATTACHMENTS_FIELD", "Attachments");
export const AIRTABLE_NOTES_TAGS_FIELD = env("VITE_AIRTABLE_NOTES_TAGS_FIELD", "tags");
export const AIRTABLE_NOTES_CREATED_AT_FIELD = env("VITE_AIRTABLE_NOTES_CREATED_AT_FIELD", "created_at");

export const AIRTABLE_TRAVELS_TABLE_NAME = env("VITE_AIRTABLE_TRAVELS_TABLE_NAME", "Travel");
export const AIRTABLE_TRAVELS_NAME_FIELD = env("VITE_AIRTABLE_TRAVELS_NAME_FIELD", "Name");
export const AIRTABLE_TRAVELS_COVER_FIELD = env("VITE_AIRTABLE_TRAVELS_COVER_FIELD", "Cover");
export const AIRTABLE_TRAVELS_USER_ID_FIELD = env("VITE_AIRTABLE_TRAVELS_USER_ID_FIELD", "user_id");
export const AIRTABLE_TRAVELS_CREATED_AT_FIELD = env("VITE_AIRTABLE_TRAVELS_CREATED_AT_FIELD", "created_at");
export const AIRTABLE_TRAVELS_DESTINATION_FIELD = env("VITE_AIRTABLE_TRAVELS_DESTINATION_FIELD", "destination");
export const AIRTABLE_TRAVELS_START_DATE_FIELD = env("VITE_AIRTABLE_TRAVELS_START_DATE_FIELD", "start_date");
export const AIRTABLE_TRAVELS_END_DATE_FIELD = env("VITE_AIRTABLE_TRAVELS_END_DATE_FIELD", "end_date");
export const AIRTABLE_TRAVELS_DESCRIPTION_FIELD = env("VITE_AIRTABLE_TRAVELS_DESCRIPTION_FIELD", "description");
export const AIRTABLE_TRAVELS_IS_VOYAGE_FIELD = env("VITE_AIRTABLE_TRAVELS_IS_VOYAGE_FIELD", "is_voyage");
export const AIRTABLE_TRAVELS_IS_PERSONAL_FIELD = env("VITE_AIRTABLE_TRAVELS_IS_PERSONAL_FIELD", "is_personal");

export const AIRTABLE_TRAVEL_BUDGET_TABLE_NAME = env("VITE_AIRTABLE_TRAVEL_BUDGET_TABLE_NAME", "TravelBudget");
export const AIRTABLE_TRAVEL_BUDGET_TRAVEL_ID_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_TRAVEL_ID_FIELD", "travel_id");
export const AIRTABLE_TRAVEL_BUDGET_CATEGORY_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_CATEGORY_FIELD", "category");
export const AIRTABLE_TRAVEL_BUDGET_LABEL_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_LABEL_FIELD", "label");
export const AIRTABLE_TRAVEL_BUDGET_ESTIMATED_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_ESTIMATED_FIELD", "estimated");
export const AIRTABLE_TRAVEL_BUDGET_ACTUAL_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_ACTUAL_FIELD", "actual");
export const AIRTABLE_TRAVEL_BUDGET_NOTES_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_NOTES_FIELD", "notes");
export const AIRTABLE_TRAVEL_BUDGET_LOCATION_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_LOCATION_FIELD", "location");
export const AIRTABLE_TRAVEL_BUDGET_IN_BUDGET_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_IN_BUDGET_FIELD", "in_budget");
export const AIRTABLE_TRAVEL_BUDGET_TO_VISIT_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_TO_VISIT_FIELD", "to_visit");
export const AIRTABLE_TRAVEL_BUDGET_SPEND_LEVEL_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_SPEND_LEVEL_FIELD", "spend_level");
export const AIRTABLE_TRAVEL_BUDGET_PURCHASED_FIELD = env("VITE_AIRTABLE_TRAVEL_BUDGET_PURCHASED_FIELD", "purchased");

export const AIRTABLE_TRAVEL_SAVINGS_TABLE_NAME = env("VITE_AIRTABLE_TRAVEL_SAVINGS_TABLE_NAME", "TravelSavings");
export const AIRTABLE_TRAVEL_SAVINGS_AMOUNT_FIELD = env("VITE_AIRTABLE_TRAVEL_SAVINGS_AMOUNT_FIELD", "amount");
export const AIRTABLE_TRAVEL_SAVINGS_AUTHOR_FIELD = env("VITE_AIRTABLE_TRAVEL_SAVINGS_AUTHOR_FIELD", "author");
export const AIRTABLE_TRAVEL_SAVINGS_DATE_FIELD = env("VITE_AIRTABLE_TRAVEL_SAVINGS_DATE_FIELD", "date");
export const AIRTABLE_TRAVEL_SAVINGS_NOTE_FIELD = env("VITE_AIRTABLE_TRAVEL_SAVINGS_NOTE_FIELD", "note");
export const AIRTABLE_TRAVEL_SAVINGS_USER_ID_FIELD = env("VITE_AIRTABLE_TRAVEL_SAVINGS_USER_ID_FIELD", "user_id");
